// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
	repositories {
		mavenCentral()
		google()
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:::ANDROID_GRADLE_PLUGIN::'

		// NOTE: Do not place your application dependencies here; they belong
		// in the individual module build.gradle files
		
		::if SET_FIREBASE_INTEGRATION:: // Lucy added 2025
		classpath 'com.google.gms:google-services:4.4.2'  // Google Services plugin
		::end::
	}
}

allprojects {
	repositories {
		mavenCentral()
		google()
	}
	
	// Added 04-08-2025 (Greg) as I was getting duplicate class errors on android - chatGPT
	// came up with this, it forces everything to use the same version of kotlin apparently.
	configurations.all {
		resolutionStrategy {
			force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
			force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
			force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
		}
	}
	
	::if ANDROID_GRADLE_BUILD_DIRECTORY::
	buildDir = "::ANDROID_GRADLE_BUILD_DIRECTORY::/::APP_FILE::/${project.name}"::end::
}

task clean(type: Delete) {
	delete rootProject.buildDir
}

wrapper {
	gradleVersion = '::ANDROID_GRADLE_VERSION::'
}

configure(subprojects.findAll {!it.file('build.gradle').exists() && it.file('build.xml').exists()}) {
	buildscript {
		repositories {
			mavenCentral()
			google()
		}

		dependencies {
			classpath 'com.android.tools.build:gradle:::ANDROID_GRADLE_PLUGIN::'
		}
	}

	apply plugin: 'android-library'

	android {
		compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
		buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION
		::if (ANDROID_GRADLE_PLUGIN>="4.0")::ndkPath '::ANDROID_NDK_ROOT_ESCAPED::'::end::
		::if (ANDROID_NDK_VERSION)::ndkVersion '::ANDROID_NDK_VERSION::'::end::

		sourceSets {
			main {
				manifest.srcFile 'AndroidManifest.xml'
				java.srcDirs = ['src']
				res.srcDirs = ['res']
			}
		}
	}

	dependencies {
		implementation project(':deps:extension-api')
	}
}
